version: '3.8'

services:
  friends-scanner:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Монтируем директорию для базы данных
      - ./data:/app/data
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Опционально: Nginx как reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - friends-scanner
    restart: unless-stopped
    profiles:
      - with-nginx
